project:
  type: website
  output-dir: docs
  
website:
  title: "Cassondra Griger"
  # image: "insert title image.png"
  # favicon: "insert icon.png"
  site-url: https://www.cassondragriger.com/
  repo-url: https://github.com/cassondragriger/mywebsite
  navbar:
    left:
      - href: aboutme.qmd
        text: About Me
      - href: cv.qmd
        text: CV
      - href: portfolio.qmd
        text: Portfolio
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/cassondragriger/
      - icon: github
        href: https://github.com/cassondragriger/mywebsite
      - icon: discord
        href: https://discordapp.com/users/UserID725207317007695912
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) using the lux theme and adapted from this [tutorial](https://github.com/jtr13/website-template). All blog posts are released under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/). All opinions and views are my own and do not represent my employer."
    left: "&copy; Copyright 2024, Cassondra Griger"

format:
  html:
    theme: lux
    css: bootstrap.min.css
    toc: true

editor: visual

